### ISSUE TITLE
Pharmacist - dispensing medicine

### ISSUE THREAD

**Issue by airdeesun** [yuzhengwen/HospitalManagementSystem#10]
1. Logic for dispensing medicine is inverted
2. medicine is case sensitive, eg 'paracetemol' vs 'Paracetemol' - couldnt dispense medicine even though there was inventory due to small letter p
3. after medicine dispensed, the option to dispense medicine for the appt still there (but status is updated), possibility to dispense medicine multiple times for the same appt if the user does not read the status properly

**Comment by dexterteo4** [comment]
medicine is case sensitive for replenishmentrequests as well
